### ISSUE TITLE
t/pod.t returns in 2.86

### ISSUE THREAD

**Issue by kentfredric** [chocolateboy/autobox#10]
https://metacpan.org/diff/file?target=CHOCOLATE/autobox-2.86/&source=CHOCOLATE%2Fautobox-2.85#t/pod.t 

https://metacpan.org/diff/file?target=CHOCOLATE/autobox-2.86/&source=CHOCOLATE%2Fautobox-2.85#MANIFEST

It appears this crept in here:

https://github.com/chocolateboy/autobox/commit/1c449658a128d689fe0f2eb6e3529d00d025a129#diff-0bf22fc49ca50df354c7619caaaa96d2R26

Despite a previous change indicating its intent to be omitted from CPAN:

https://github.com/chocolateboy/autobox/commit/02ca98bbf33a3c0b05596138d30539246aafe2d8#diff-0bf22fc49ca50df354c7619caaaa96d2

**Comment by chocolateboy** [comment]
@kentfredric Good catch, thanks! Fixed [here](https://github.com/chocolateboy/autobox/commit/fac588b91e56d6d0b6c00f1bcfe86bbac03c1c40).
