### ISSUE TITLE
version.pm must be used to support version tuples on perl 5.8

### ISSUE THREAD

**Issue by Grinnz** [chocolateboy/autobox#11]
version.pm is not used for core version comparisons until 5.10 or if it's loaded. So to support 5.8, version tuples should be declared like (on a single line):

    use version 0.77; our $VERSION = version->declare('v3.0.0');

and version should be added to your module's runtime dependencies. See http://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html under Declaring Versions, and https://metacpan.org/pod/version#How-to-declare()-a-dotted-decimal-version.

**Comment by chocolateboy** [comment]
Thanks. What do I need to change in autobox?

**Comment by Grinnz** [comment]
Just the version declaration in autobox.pm as 
above (corrected in an edit) (https://github.com/chocolateboy/autobox/blob/master/lib/autobox.pm#L14) and to add version (at least '0.77') to PREREQ_PM in your Makefile.PL.

**Comment by chocolateboy** [comment]
Thanks! Applied in v3.0.1.
