### ISSUE TITLE
Could you make $el ~~ \@array work somehow?

### ISSUE THREAD

**Issue by akarelas** [chocolateboy/autobox#7]
In Perl 5.27.7 the right-hand side of the ~~ operator is supposed to be an object that has ~~ overloaded. So I thought that overloading ~~ on package ARRAY would let me create arrays' behaviour with ~~ as I wanted. But I found out that that does not do the trick (see my program here: https://gist.github.com/akarelas/feb1a870da15b1e729ebe718ede4d6ce )

I wonder if autobox could be modified to handle ~~ as well, or maybe there's a way to achieve what I want which I just don't know.

**Comment by chocolateboy** [comment]
No, it's not possible. As described [here](https://stackoverflow.com/a/5137373), autobox just lexically overrides the [arrow operator](http://search.cpan.org/perldoc?perlop#The_Arrow_Operator). It doesn't bless primitives into objects, so overloading, or any other kind of "magic" which depends on values being blessed, doesn't work.

I'm not sure from your gist what missing functionality you're trying to add (and I can't reproduce that error with perl 5.26.1, the latest stable release).
 
If you're looking to use a [sane/simple](https://stackoverflow.com/a/16930588) version of smart-matching on legacy perls, I used to use this:

* https://metacpan.org/pod/match::simple

If you want to promote an array to an object whose package you can add a custom `~~` overload to, there are several packages for that e.g.:

* https://metacpan.org/pod/Class::Builtin
* https://metacpan.org/pod/Data::Object
* https://metacpan.org/pod/Object::Hybrid

And there are a couple of packages which export functions which "cast" arrays, arrayrefs and code blocks into matcher objects which DWYM e.g.:

* https://metacpan.org/pod/Smart::Match
* https://metacpan.org/pod/Sub::Go

**Comment by akarelas** [comment]
Thanks for your reply. The error I described above only occurs on Perl 5.27.7 and later, where the ~~ operator is undefined except on objects that overload it.

**Comment by chocolateboy** [comment]
P.S.

> I wonder if autobox could be modified to handle ~~ as well

Yes, it probably could... Though I'm not sure it should be. (Why just that operator? What about the others? Why not just [use Ruby](https://www.skorks.com/2009/08/how-a-ruby-case-statement-works-and-what-you-can-do-with-it/)? :-))

I haven't investigated, but I doubt there's a central hook that can be intercepted to check for overloads on all operands, so one would need to be written for every operator.

That said, I imagine it would be possible (and possibly useful) to build a module for a single operator like `~~` (e.g. [autobox::smartmatch](http://search.cpan.org/perldoc?autobox#import)) which leverages autobox's "type system" to DWYM.

**Comment by akarelas** [comment]
I heard on Twitter that perl 5.27.8 just reverted this change, at least for now. We'll see.
